language: java

branches:
  only:
  - master
  - develop

jdk: oraclejdk8
  
sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer
  
script:
  - mvn clean compile assembly:single
  
