
host: 127.0.0.1
port: 4009

# project definitions
baseurl: /MinimaxSimulator
topnav_title: Minimax Simulator
homepage_title: Minimax Simulator
site_title: Minimax Simulator
company_name: Leibniz Universität Hannover, Institut für Systems Engineering, Fachgebiet System- und Rechnerarchitektur
footer_image_location: /images/luh_ise_sra.png

# variables
sidebar_tagline: mmsim
sidebar_image_location: /images/exe-icon.png
sidebar_version: Version 1.2.1
theme_file: theme-blue.css

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
